version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8007
      - REACT_APP_PRODUCT_API_URL=http://localhost:8001
    depends_on:
      - user-service
      - product-service

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=user_service
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./user_service:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8007 --reload

  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./product_service.db
    volumes:
      - ./product_service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
